### ISSUE TITLE
Any way to replace every string matching the regexp?

### ISSUE THREAD

**Issue by Antonhansel** [yoniholmes/grunt-text-replace#44]
```
replace: {
      lang: {
        src: ['index.html'],
        dest: ['dist/index.html'],
        replacements: [{
          from: /%([^}]*)%/, //Match %test%
          to: function(matchedWord) {
            matchedWord = matchedWord.substring(1, matchedWord.length - 1);
            return strings.index[matchedWord] ? strings.index[matchedWord] : matchedWord;
          }
        }]
      }
    },

```

I have 100+ strings I want to replace using config files to change the language of my app.
I'm not sure, but I don't think this could be done using grunt-text-replace, am I wrong?

**Comment by yoniholmes** [comment]
Hi Anton, thanks for your message. Sorry for the late response. I'm not sure I follow exactly what you wish to do. Are you saying that you have some HTML pages with `%words-to-translate%` delimited with `%` characters, and you wish to replace those words with translations that match the keys in a config file? Yes I don't see why you can't do that. 

Your regex looks a bit suspicious though. I wouldn't recommend using `[^` because it will match all characters including new lines'. If your keys are always alpha-numeric then you probably want: `/%([a-zA-Z0-9]+)%/g`. Note: I used the global flag also. You can add `_` or `-` characters if you need those as well:  `/%([a-zA-Z0-9-_]+)%/g`.

Finally, inside the callback, note that there are several arguments. 

``` javascript
...
from: /%([a-zA-Z0-9-_]+)%/g,
to: function (matchedWord, index, fullText, regexMatches) {
  var wordKey = regexMatches[0] 
  var translatedWord = myTranslations[wordKey]
  return translatedWord
}
```

Does that answer your question? 

Many thanks, 

Jonathan
