### ISSUE TITLE
some trouble with the overwritting

### ISSUE THREAD

**Issue by OlivierVT** [yoniholmes/grunt-text-replace#45]
Hello,
I'm currently busy to create my own grunt workflow but I've some trouble when I have to replace some strings. I'm not so good using Javascript but I understand it in a general way (sorry guys :/)

Everything in my worlflow works (at least I don't have any errors in my shell) and the task ends in a good way : "Done, without errors." (hourra)

Except that the path to my img folder and the path to my Js folder never change in my file, but the css path well. Here is the part for the "text-replace"

If I can have some advice from people ? Or the explanation of my mistakes ? Thanks a lot for the people who will answer to it.

Have a nice day and Merry Christmas (yeah a little bit in advance :) )

replace:{  
    img_css:{
        src:'<%= project.src %>/css/_.css',
        overwrite:true,
      replacements:[{
          from:['<%= project.src %>/img/','../<%= project.src %>/img/'],
          to:'<%= project.app %>/img/'
      }],
  },
    img:{
      src:['_.html','_.php','__/_.php'],  
      overwrite:true,
      replacements:[{
          from:['<%= project.src %>/img/','../<%= project.src %>/img/'],
          to:'<%= project.app %>/img/'
      }],
  },
    css:{
        src:['_.html','_.php','**/_.php'],
        overwrite:true,
        replacements:[{
            from:'<link rel="stylesheet" href="<%= project.src %>/css/app.css">',
            to:'<link rel="stylesheet" href="<%= project.app %>/css/app.min.css">'
        }],
    },
    js:{
        src:['_.html','*.php','**/_.php','app/inc/_.php'],
        overwrite:true,
        replacements:[{
            from:['<script src="<%= project.src %>/js/lib/_.js"></script>','<script src="<%= project.src %>/js/_.js"></script>'],
            to:'<script src="<%= project.app %>/js/app.min.js"></script>'
        }],
    },
}

**Comment by yoniholmes** [comment]
Hi Olivier, thanks for the message. I'm not entirely clear what you're trying to achieve, but I can see some errors in your setup.

I suggest implementing one replacement first, and verifying that it works, rather than implement three (I see you have `img_css`, `img` and `css`.

In two of your examples I see that you're assigning an array to the `from` property, that won't work. `from` only accepts a string or regular expression. If you have multiple patterns that you want to replace with the same string then you can either list multiple 'replacement' objects, or use a regular expression.

Here's an example:

``` javascript
replace: {
  img_css: {
    src: '<%= project.src %>/css/.css',
    overwrite: true,
    replacements:[{
      from: '<%= project.src %>/img/',
      to: '<%= project.app %>/img/'
    }, {
      from: '../<%= project.src %>/img/',
      to: '<%= project.app %>/img/'
    }],
  }
}
```

Or with a regular expression:

``` javascript
replace: {
  img_css: {
    src: '<%= project.src %>/css/.css',
    overwrite: true,
    replacements:[{
      from: /(\.\.\/){0,1}<%= project\.src %>/img/g,
      to: '<%= project.app %>/img/'
    }],
  }
}
```

The final point is, I'm not sure what you're trying to match with `'<%= project.src %>/img/'` in the `from` field. The from string doesn't get expanded so, `grunt-text-replace` will be looking for the actual string `'<%= project.src %>/img/'` as opposed to something like `/my/path/img/`. If you wanted that you could do:  `project.src + '/img/'`.

I hope the above steers you in the right direction! Good luck with it!

Cheers & Merry Christmas to you too,

Jonathan
